name: parent

on:
  workflow_dispatch:

jobs:
  job1:
    uses: /.github/workflows/automated_test_wf.yml@v1
    
 # job2:
 #   runs-on: ubuntu-latest
 #   needs: job1
 #   steps:
 #     - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
